'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://services.nationalmap.gov/arcgis/services/WFS/geonames/MapServer/WFSServer?"& _ 
            "request=GetCapabilities&service=WFS")>  _
        Public Property URLNationalMap() As String
            Get
                Return CType(Me("URLNationalMap"),String)
            End Get
            Set
                Me("URLNationalMap") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://api.openweathermap.org/data/2.5/weather?lat=43.6&lon=-73.5")>  _
        Public Property URLWeather() As String
            Get
                Return CType(Me("URLWeather"),String)
            End Get
            Set
                Me("URLWeather") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://maps.googleapis.com/maps/api/directions/json?origin=42.66094,-73.79817&des"& _ 
            "tination=42.65854,-73.79584")>  _
        Public Property UTLDirectionTest() As String
            Get
                Return CType(Me("UTLDirectionTest"),String)
            End Get
            Set
                Me("UTLDirectionTest") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://mwilson:mwilson123@50.19.85.246/devsample/apiv1.svc/databases/1/schools")>  _
        Public Property URLSchoolsList() As String
            Get
                Return CType(Me("URLSchoolsList"),String)
            End Get
            Set
                Me("URLSchoolsList") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://mwilson:mwilson123@50.19.85.246/devsample/apiv1.svc/databases/1/schools/<s"& _ 
            "choolid>/trips")>  _
        Public Property URLTripsList() As String
            Get
                Return CType(Me("URLTripsList"),String)
            End Get
            Set
                Me("URLTripsList") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<schoolid>")>  _
        Public Property schoolIDReplaceString() As String
            Get
                Return CType(Me("schoolIDReplaceString"),String)
            End Get
            Set
                Me("schoolIDReplaceString") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("mwilson:mwilson123")>  _
        Public Property myAuthCode() As String
            Get
                Return CType(Me("myAuthCode"),String)
            End Get
            Set
                Me("myAuthCode") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://mwilson:mwilson123@50.19.85.246/devsample/apiv1.svc/databases/1/trips/<tri"& _ 
            "pid>/stops")>  _
        Public Property URLStopsList() As String
            Get
                Return CType(Me("URLStopsList"),String)
            End Get
            Set
                Me("URLStopsList") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<tripid>")>  _
        Public Property tripIDReplaceString() As String
            Get
                Return CType(Me("tripIDReplaceString"),String)
            End Get
            Set
                Me("tripIDReplaceString") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://maps.googleapis.com/maps/api/directions/json?origin=<originLatLon>&destina"& _ 
            "tion=<destinationLatLon>")>  _
        Public Property URLDirections() As String
            Get
                Return CType(Me("URLDirections"),String)
            End Get
            Set
                Me("URLDirections") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<originLatLon>")>  _
        Public Property URLDirectionsReplaceOriginLatLon() As String
            Get
                Return CType(Me("URLDirectionsReplaceOriginLatLon"),String)
            End Get
            Set
                Me("URLDirectionsReplaceOriginLatLon") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<destinationLatLon>")>  _
        Public Property URLDirectionsReplaceDestinationLatLon() As String
            Get
                Return CType(Me("URLDirectionsReplaceDestinationLatLon"),String)
            End Get
            Set
                Me("URLDirectionsReplaceDestinationLatLon") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://maps.googleapis.com/maps/api/streetview?size=300x200&location=<loclat>,<l"& _ 
            "oclon>&heading=<locheading>&key=AIzaSyAX7KWj1v1qgmDeDN7eeg2DFqjStTuTArs")>  _
        Public Property URLStreetView() As String
            Get
                Return CType(Me("URLStreetView"),String)
            End Get
            Set
                Me("URLStreetView") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<loclat>")>  _
        Public Property URLStreetViewLatReplaceString() As String
            Get
                Return CType(Me("URLStreetViewLatReplaceString"),String)
            End Get
            Set
                Me("URLStreetViewLatReplaceString") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<loclon>")>  _
        Public Property URLStreetViewLonReplaceString() As String
            Get
                Return CType(Me("URLStreetViewLonReplaceString"),String)
            End Get
            Set
                Me("URLStreetViewLonReplaceString") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<locheading>")>  _
        Public Property URLStreetViewHeadingReplaceString() As String
            Get
                Return CType(Me("URLStreetViewHeadingReplaceString"),String)
            End Get
            Set
                Me("URLStreetViewHeadingReplaceString") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.WebServiceUrl),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://50.19.85.246/devsample/apiv1.svc/databases/1/trips/stops/<stopid>")>  _
        Public Property URLOneStop() As String
            Get
                Return CType(Me("URLOneStop"),String)
            End Get
            Set
                Me("URLOneStop") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("<stopid>")>  _
        Public Property stopIDReplaceString() As String
            Get
                Return CType(Me("stopIDReplaceString"),String)
            End Get
            Set
                Me("stopIDReplaceString") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("80")>  _
        Public Property sideWindowOffset() As Integer
            Get
                Return CType(Me("sideWindowOffset"),Integer)
            End Get
            Set
                Me("sideWindowOffset") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.TestApp1.My.MySettings
            Get
                Return Global.TestApp1.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
